### ISSUE TITLE
🐛 TextStyle will override the default font

### ISSUE THREAD

**Issue by MasterHiei** [bdlukaa/fluent_ui#438]
**Describe the bug**
TextStyle will override the default font.

**To Reproduce**
1. Set and declare the font in 'pubspec.yaml'
```yaml
 flutter:
  uses-material-design: true

  fonts:
    - family: ACustomFont
      fonts:
        - asset: fonts/ACustomFont-Regular.ttf
          weight: 400
        - asset: fonts/ACustomFont-Bold.ttf
          weight: 700
 ```
2. Set as the default
```dart
return FluentApp.router(
      theme: ThemeData(
        fontFamily: 'ACustomFont',
      ),
      darkTheme: ThemeData(
        fontFamily: 'ACustomFont',
      ),
      // ...
    );
 ```
3. Running app
4. Add a text widgets like below and it is looks fine
```dart
Text('lorem')
```
5. Set a custom TextStyle
```dart
Text('lorem', style: TextStyle(fontSize: 16))
```
6. The text font rolls back to Flutter default font
7. Update the fontFamily and everything is back
```dart
Text('lorem', style: TextStyle(fontSize: 16, fontFamily: 'ACustomFont'))
```

Is this the expected behavior?
