### ISSUE TITLE
Shift+Tab navigation with AutoSuggestBox 🐛 

### ISSUE THREAD

**Issue by Michal-MK** [bdlukaa/fluent_ui#894]
**Describe the bug**
I have two `AutoSuggestBox`es in a `Row`

```dart
import 'package:fluent_ui/fluent_ui.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return FluentApp(
      theme: FluentThemeData(),
      home: Row(
        children: [
          const Expanded(
            child: AutoSuggestBox(
              autofocus: true,
              items: [],
            ),
          ),
          Expanded(
            child: AutoSuggestBox(
              items: [
                AutoSuggestBoxItem(value: "Some Item", label: "Some Item"),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

The first one is focused. When I press Tab the focus moves to the next one -> ✅ 
The second one is focused now. When I press Shift+Tab i expect to move back to the first one. But instead the second one is "re-focused", the overlay with the suggestions blinks and the focus does not change. -> 🟥 
The second one is still focused. Pressing Tab moves to the first -> ✅  (Since there are only 2 the focus loops that is expected.)

**Additional context**
```yaml
name: src
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```
