### ISSUE TITLE
Text Selection color not respecting brightness (Missing TextSelectionThemeData equivalent)🐛 

### ISSUE THREAD

**Issue by Michal-MK** [bdlukaa/fluent_ui#897]
**Describe the bug**
When selecting text in e.g. a `TextBox`, the selected text color does not match adjust based on accent brightness.

Setting "blue" theme color in Windows:
<img width="644" alt="image" src="https://github.com/bdlukaa/fluent_ui/assets/12874766/0883dbe1-9e31-4dcc-acc9-6a329af4b925">

Results in:
<img width="202" alt="image" src="https://github.com/bdlukaa/fluent_ui/assets/12874766/4e190273-7b86-4ce5-9731-c06a0d58fa21">

While in Flutter:
<img width="91" alt="image" src="https://github.com/bdlukaa/fluent_ui/assets/12874766/21633818-3f71-4618-8466-10c7e9997717">

The text stays black making it hard to read due to low contrast. In the `FluentThemeData` I found that there is no option to change text selection color, only the `accentColor` is used instead.

**Expected behavior**
Text on dark accent colors should be white.

```yaml
environment:
  sdk: '>=3.0.1 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^4.7.0
 ```
